### ISSUE TITLE
Fields that expect an array get null (rather than left blank) when given empty content.

### ISSUE THREAD

**Issue by wesort** [riasvdv/statamic-data-import#16]
An empty 'cell' in the `.csv` import for a `related_film` column (fieldtype: `entries`) will create an array with `null`. 
```
related_film:
  - null
```

The expected result should be the field is skipped in the import. 

The problem with the `null` is that it _breaks_ (is that the right term??) the field in the CP. 
![null in a entries field](https://user-images.githubusercontent.com/3920126/165468755-52131e45-6031-46cf-81d3-b0b77a84ecc5.png)

**Comment by riasvdv** [comment]
Should be fixed in 1.2.1!

**Comment by wesort** [comment]
Only just getting a chance to test this and unfortunately I'm still seeing the issue.

### Example `.csv` content:
```
blueprint,title,still_image,related_film,digital_formats
stills,_Test import 01,_test-card-01.png,,jpg|tiff
```

### Resulting `.md` content file:
```
---
id: 3099d691-6bdc-4cf6-854f-314488fe60dc
blueprint: stills
title: '_Test import 01'
still_image: _test-card-01.png
related_film:
  - ''
digital_formats:
  - jpg
  - tiff
---
```

### FYI
`statamic/cms: v3.3.12`
`rias/statamic-data-import 1.2.1`

Could share a private repo if that helps.

**Comment by riasvdv** [comment]
The value was `""` and not `null`, so that was causing it, should be fixed in 1.2.2
